/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class spreadtrum_zhongjihao_aacanaiysisandroid_swig_SwigTest */

#ifndef _Included_spreadtrum_zhongjihao_aacanaiysisandroid_swig_SwigTest
#define _Included_spreadtrum_zhongjihao_aacanaiysisandroid_swig_SwigTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     spreadtrum_zhongjihao_aacanaiysisandroid_swig_SwigTest
 * Method:    SayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_spreadtrum_zhongjihao_aacanaiysisandroid_swig_SwigTest_SayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
